name: 'Destroy all ALZ Resources'
on:
    workflow_dispatch:

env:
  ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
  ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
  ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
  WORKDIR: 'environments/sandbox'

jobs:
  plan:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORKDIR}}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v4

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve